/**
 * Языки TranslateGemma: код → английское название (то, что подставляет шаблон модели).
 * Список взят из chat_template.jinja google/translategemma-4b-it.
 */
export const LANGUAGES: Record<string, string> = {
  aa: "Afar",
  ab: "Abkhazian",
  af: "Afrikaans",
  ak: "Akan",
  am: "Amharic",
  an: "Aragonese",
  ar: "Arabic",
  as: "Assamese",
  az: "Azerbaijani",
  ba: "Bashkir",
  be: "Belarusian",
  bg: "Bulgarian",
  bm: "Bambara",
  bn: "Bengali",
  bo: "Tibetan",
  br: "Breton",
  bs: "Bosnian",
  ca: "Catalan",
  ce: "Chechen",
  co: "Corsican",
  cs: "Czech",
  cv: "Chuvash",
  cy: "Welsh",
  da: "Danish",
  de: "German",
  dv: "Divehi",
  dz: "Dzongkha",
  ee: "Ewe",
  el: "Greek",
  en: "English",
  eo: "Esperanto",
  es: "Spanish",
  et: "Estonian",
  eu: "Basque",
  fa: "Persian",
  ff: "Fulah",
  fi: "Finnish",
  fo: "Faroese",
  fr: "French",
  fy: "Western Frisian",
  ga: "Irish",
  gd: "Scottish Gaelic",
  gl: "Galician",
  gn: "Guarani",
  gu: "Gujarati",
  gv: "Manx",
  ha: "Hausa",
  he: "Hebrew",
  hi: "Hindi",
  hr: "Croatian",
  ht: "Haitian",
  hu: "Hungarian",
  hy: "Armenian",
  ia: "Interlingua",
  id: "Indonesian",
  ie: "Interlingue",
  ig: "Igbo",
  ii: "Sichuan Yi",
  ik: "Inupiaq",
  io: "Ido",
  is: "Icelandic",
  it: "Italian",
  iu: "Inuktitut",
  ja: "Japanese",
  jv: "Javanese",
  ka: "Georgian",
  ki: "Kikuyu",
  kk: "Kazakh",
  kl: "Kalaallisut",
  km: "Central Khmer",
  kn: "Kannada",
  ko: "Korean",
  ks: "Kashmiri",
  ku: "Kurdish",
  kw: "Cornish",
  ky: "Kyrgyz",
  la: "Latin",
  lb: "Luxembourgish",
  lg: "Ganda",
  ln: "Lingala",
  lo: "Lao",
  lt: "Lithuanian",
  lu: "Luba-Katanga",
  lv: "Latvian",
  mg: "Malagasy",
  mi: "Maori",
  mk: "Macedonian",
  ml: "Malayalam",
  mn: "Mongolian",
  mr: "Marathi",
  ms: "Malay",
  mt: "Maltese",
  my: "Burmese",
  nb: "Norwegian Bokmål",
  nd: "North Ndebele",
  ne: "Nepali",
  nl: "Dutch",
  nn: "Norwegian Nynorsk",
  no: "Norwegian",
  nr: "South Ndebele",
  nv: "Navajo",
  ny: "Chichewa",
  oc: "Occitan",
  om: "Oromo",
  or: "Oriya",
  os: "Ossetian",
  pa: "Punjabi",
  pl: "Polish",
  ps: "Pashto",
  pt: "Portuguese",
  qu: "Quechua",
  rm: "Romansh",
  rn: "Rundi",
  ro: "Romanian",
  ru: "Russian",
  rw: "Kinyarwanda",
  sa: "Sanskrit",
  sc: "Sardinian",
  sd: "Sindhi",
  se: "Northern Sami",
  sg: "Sango",
  si: "Sinhala",
  sk: "Slovak",
  sl: "Slovenian",
  sn: "Shona",
  so: "Somali",
  sq: "Albanian",
  sr: "Serbian",
  ss: "Swati",
  st: "Southern Sotho",
  su: "Sundanese",
  sv: "Swedish",
  sw: "Swahili",
  ta: "Tamil",
  te: "Telugu",
  tg: "Tajik",
  th: "Thai",
  ti: "Tigrinya",
  tk: "Turkmen",
  tl: "Tagalog",
  tn: "Tswana",
  to: "Tonga",
  tr: "Turkish",
  ts: "Tsonga",
  tt: "Tatar",
  ug: "Uyghur",
  uk: "Ukrainian",
  ur: "Urdu",
  uz: "Uzbek",
  ve: "Venda",
  vi: "Vietnamese",
  vo: "Volapük",
  wa: "Walloon",
  wo: "Wolof",
  xh: "Xhosa",
  yi: "Yiddish",
  yo: "Yoruba",
  za: "Zhuang",
  zh: "Chinese",
  zu: "Zulu",
  "fil-PH": "Filipino",
  "zh-Hant": "Chinese",
  "pt-BR": "Portuguese",
  "pt-PT": "Portuguese",
};

export const isLang = (code: string): boolean =>
  Object.prototype.hasOwnProperty.call(LANGUAGES, code);

/** Код TranslateGemma → язык Tesseract (OCR). Нет в таблице — OCR недоступен для языка. */
export const TESS_LANG: Record<string, string> = {
  en: "eng",
  ru: "rus",
  uk: "ukr",
  be: "bel",
  bg: "bul",
  de: "deu",
  fr: "fra",
  es: "spa",
  it: "ita",
  pt: "por",
  "pt-BR": "por",
  "pt-PT": "por",
  nl: "nld",
  pl: "pol",
  cs: "ces",
  sk: "slk",
  sl: "slv",
  hr: "hrv",
  sr: "srp",
  ro: "ron",
  hu: "hun",
  fi: "fin",
  sv: "swe",
  da: "dan",
  nb: "nor",
  no: "nor",
  tr: "tur",
  el: "ell",
  he: "heb",
  ar: "ara",
  fa: "fas",
  hi: "hin",
  bn: "ben",
  ta: "tam",
  te: "tel",
  th: "tha",
  vi: "vie",
  id: "ind",
  ms: "msa",
  ja: "jpn",
  ko: "kor",
  zh: "chi_sim",
  "zh-Hans": "chi_sim",
  "zh-Hant": "chi_tra",
  "zh-TW": "chi_tra",
  lt: "lit",
  lv: "lav",
  et: "est",
  ka: "kat",
  hy: "hye",
  kk: "kaz",
  az: "aze",
  ca: "cat",
  eu: "eus",
  gl: "glg",
  is: "isl",
  ga: "gle",
  cy: "cym",
  af: "afr",
  sq: "sqi",
  mk: "mkd",
  mt: "mlt",
  la: "lat",
  ur: "urd",
  ne: "nep",
  mr: "mar",
  gu: "guj",
  kn: "kan",
  ml: "mal",
  my: "mya",
  km: "khm",
  lo: "lao",
  si: "sin",
};

const STOP: Record<string, string[]> = {
  en: ["the", "and", "of", "to", "is", "in", "that", "it", "for", "with"],
  de: ["der", "die", "und", "das", "ist", "nicht", "ein", "zu", "mit", "auf"],
  fr: ["le", "la", "les", "et", "des", "est", "une", "que", "pour", "dans"],
  es: ["el", "la", "los", "de", "que", "y", "en", "una", "por", "con"],
  it: ["il", "di", "che", "e", "la", "per", "un", "non", "con", "sono"],
  pt: ["o", "de", "que", "e", "do", "da", "em", "um", "para", "não"],
  nl: ["de", "het", "een", "en", "van", "dat", "niet", "is", "op", "te"],
  pl: ["nie", "to", "się", "na", "jest", "że", "w", "z", "do", "jak"],
  tr: ["bir", "ve", "bu", "için", "ile", "da", "de", "çok", "daha", "ne"],
};

/**
 * Грубое определение языка для режима «авто»: по письменности, а для латиницы —
 * по частоте служебных слов. Для точного результата язык лучше указать вручную.
 */
export function detectLanguage(text: string): string {
  const s = text.slice(0, 4000);
  const count = (re: RegExp): number => (s.match(re) || []).length;
  const scripts: [string, number][] = [
    ["ru", count(/[\u0400-\u04FF]/g)],
    ["ja", count(/[\u3040-\u30FF]/g)],
    ["ko", count(/[\uAC00-\uD7AF]/g)],
    ["zh", count(/[\u4E00-\u9FFF]/g)],
    ["ar", count(/[\u0600-\u06FF]/g)],
    ["he", count(/[\u0590-\u05FF]/g)],
    ["hi", count(/[\u0900-\u097F]/g)],
    ["th", count(/[\u0E00-\u0E7F]/g)],
    ["el", count(/[\u0370-\u03FF]/g)],
    ["ka", count(/[\u10A0-\u10FF]/g)],
  ];
  scripts.sort((a, b) => b[1] - a[1]);
  if (scripts[0][1] > 0) {
    // Кана важнее иероглифов: в японском текст смешан, а в китайском каны нет.
    if (scripts[0][0] === "zh" && count(/[\u3040-\u30FF]/g) > 0) return "ja";
    if (scripts[0][0] === "ru" && count(/[іїєґ]/gi) > 0) return "uk";
    return scripts[0][0];
  }
  const words = s.toLowerCase().match(/[\p{L}']+/gu) || [];
  let best = "en";
  let bestScore = -1;
  for (const [lang, list] of Object.entries(STOP)) {
    const set = new Set(list);
    const score = words.filter((w) => set.has(w)).length;
    if (score > bestScore) {
      best = lang;
      bestScore = score;
    }
  }
  return best;
}
