import type { UIKey } from "@/pages/myspace/m3e/lib/i18n";

/**
 * Русский интерфейс редактора. Оригинал знает ja / en / zh / ko; русский — надстройка над английским:
 * содержимое экранов и промпт остаются на английском, а подписи панелей, кнопок и подсказок переводятся.
 * Ключ, которого здесь нет, показывается по-английски.
 */
export const RU: Partial<Record<UIKey, string>> = {
  parts: "Элементы",
  layers: "Слои",
  edit: "Правка",
  prompt: "Промпт",
  closePanel: "Закрыть панель",
  search: "Поиск",
  favorites: "Избранное",
  addFavorite: "В избранное",
  removeFavorite: "Убрать из избранного",
  clear: "Очистить",
  language: "Язык",
  select: "Выбор",
  hand: "Рука",
  blank: "Пустой холст",
  phone: "Экраны телефона",
  addFrame: "Добавить экран",
  preview: "Предпросмотр",
  zoomIn: "Приблизить",
  zoomOut: "Отдалить",
  fit: "Вписать",
  undo: "Отменить",
  redo: "Повторить",
  clearAll: "Очистить холст",
  clearAllTitle: "Очистить холст?",
  clearAllBody: "Все экраны и элементы будут удалены. Вернуть их можно отменой (Ctrl+Z).",
  screen: "Экран",
  screenName: "Название экрана",
  name: "Название",
  background: "Фон",
  export: "Экспорт",
  project: "Проект",
  saveProject: "Сохранить проект",
  openProject: "Открыть проект",
  replaceProjectTitle: "Открыть этот проект?",
  askAi: "Спросить ИИ",
  askAiHint:
    "Опишите, что нужно, и нажмите «Набросать с ИИ»: модель из вкладки ИИ нарисует дизайн на холсте. Или скопируйте инструкцию для ИИ-агента (например, Claude Code), откройте ссылку из его ответа или сохраните его JSON и загрузите через «Открыть проект».",
  askAiIdea: "Что сделать (например, приложение для хранения и поиска рецептов)",
  askAiIdeaFallback: "(опишите здесь, что сделать)",
  askAiCopy: "Скопировать инструкцию",
  askAiText:
    "Make an M3E Canvas sketch. First read {url} and follow it: build the design as JSON and reply with a share link. If you cannot run code, reply with the JSON in a code block (it will be saved to a file and opened). No verification is needed.\n\nWhat to build: {idea}",
  askAiGenerate: "Набросать с ИИ",
  askAiPasted: "Вставьте это в своего ИИ-агента",
  askAiTitle: "Попросить ИИ о дизайне",
  askAiCopyTitle: "Инструкция для ИИ-агента",
  askAiGenerateTitle: "Использует ключ из вкладки ИИ",
  aiSetup: "Настройки ИИ",
  aiSetupHint: "Добавьте ключ, чтобы набрасывать прямо здесь",
  aiSetupTitle: "Открыть вкладку ИИ",
  draftKeep: "Оставить этот дизайн",
  draftUndo: "Вернуть прежний дизайн",
  askAiGenerating: "Набрасываю…",
  selectedTab: "Выбрано",
  shareLinkCopy: "Скопировать ссылку",
  shareLinkHint: "Ссылка, открывающая этот дизайн (без картинок)",
  replaceProject: "Текущий холст будет заменён. Отмена (Ctrl+Z) вернёт его.",
  invalidProject: "Не удалось открыть файл проекта.",
  readOnlyTitle: "Редактирование в другой вкладке",
  readOnlyBody: "Этот холст редактируется в другой вкладке. Закройте её и перезагрузите страницу.",
  reload: "Перезагрузить",
  copied: "Скопировано",
  saveImage: "Сохранить как картинку",
  saving: "Сохраняю…",
  previewFrom: "Предпросмотр с этого экрана",
  duplicate: "Дублировать",
  more: "Ещё",
  delete: "Удалить",
  deleteSelection: "Удалить выбранное",
  text: "Текст",
  label: "Подпись",
  bold: "Жирный",
  action: "Действие",
  supporting: "Пояснение",
  tabs: "Пункты",
  options: "Варианты",
  addOption: "Добавить вариант",
  removeOption: "Убрать вариант",
  addTab: "Добавить вкладку",
  selectedOption: "Начальное значение",
  changeIcon: "Сменить иконку",
  image: "Картинка",
  pickImage: "Выбрать картинку",
  removeImage: "Убрать картинку",
  imageUrl: "Адрес картинки",
  imageFailed: "Не удалось прочитать картинку",
  imageTop: "Сверху",
  imageBottom: "Снизу",
  imageLeading: "Слева",
  imageTrailing: "Справа",
  imageBehind: "Под текстом",
  cardLayout: "Раскладка",
  noImageLayout: "Без картинки",
  textPosition: "Положение текста",
  textTop: "Сверху",
  textMiddle: "По центру",
  textBottom: "Снизу",
  textStart: "К началу",
  textCenter: "По центру",
  textEnd: "К концу",
  imageSize: "Размер картинки",
  textColor: "Цвет текста",
  autoWidth: "Авто",
  icon: "Иконка",
  noIcon: "Без иконки",
  searchIcons: "Поиск иконок",
  style: "Стиль",
  filled: "Залитый",
  tonal: "Тональный",
  elevated: "С тенью",
  outlined: "С контуром",
  standard: "Обычный",
  vibrant: "Яркий",
  styleSurface: "Поверхность",
  stylePrimary: "Основной",
  styleSecondary: "Дополнительный",
  state: "Состояние",
  railState: "Состояние рейла",
  railCollapsed: "Свёрнут",
  railExpanded: "Развёрнут",
  railStandard: "В макете",
  railModal: "Поверх экрана",
  expandNavigation: "Развернуть навигацию",
  collapseNavigation: "Свернуть навигацию",
  selected: "Выбрано",
  handle: "Ручка",
  switchOff: "Переключатель выключен",
  switchOn: "Переключатель включён",
  on: "Вкл.",
  container: "Контейнер",
  wavy: "Волнистый",
  trackThickness: "Толщина дорожки",
  partType: "Тип",
  progressLoop: "Зациклить",
  progressPercent: "Процент",
  progressState: "Прогресс",
  noTrigger: "Нажатие на этот элемент ничего не открывает",
  noMatch: "Нет подходящих элементов",
  noIcons: "Нет подходящих иконок",
  loading: "Загрузка…",
  progressBar: "Полоса",
  progressRing: "Кольцо",
  progressWavyBar: "Волнистая полоса",
  progressWavyRing: "Волнистое кольцо",
  determinate: "С процентом",
  size: "Размер",
  width: "Ширина",
  height: "Высота",
  fontSize: "Размер шрифта",
  cornerRadius: "Радиус углов",
  cornerTop: "Верхние углы",
  cornerBottom: "Нижние углы",
  cornerLeft: "Левые углы",
  cornerRight: "Правые углы",
  cornersEach: "Каждый угол",
  cornerTl: "Левый верхний",
  cornerTr: "Правый верхний",
  cornerBl: "Левый нижний",
  cornerBr: "Правый нижний",
  screenWidth: "На весь экран",
  contentWidth: "Обычная",
  halfWidth: "Половина",
  columnWidth: "Один столбец телефона",
  screenHeight: "Высота экрана",
  halfHeight: "Пол-экрана",
  tapTo: "Действие по нажатию",
  none: "Нет",
  goBack: "Назад",
  swipeTo: "Свайп открывает",
  toggle: "Кнопка-переключатель",
  toggleHint: "Нажатие включает и выключает",
  behavior: "Поведение",
  whenPressed: "Что происходит при нажатии…",
  whatItDoes: "Что делает этот элемент…",
  removeLink: "Убрать связь",
  group: "Группа",
  makeGroup: "Сгруппировать",
  ungroup: "Разгруппировать",
  selectedParts: "выбрано",
  groupHint: "Сохраняет перекрытия и двигается как один слой",
  noBackground: "Без фона",
  normalState: "Обычное",
  onState: "Включено",
  groupEditNote: "Разгруппируйте, чтобы править элементы внутри",
  openPanel: "Открыть панель",
  colors: "Цвета",
  templates: "Палитры",
  customColor: "Свой",
  seedColor: "Основной цвет",
  seedHint: "Один цвет строит всю схему Material 3. «Тонкая настройка» меняет отдельные роли.",
  useThis: "Применить",
  fineTune: "Тонкая настройка",
  dynamicColor: "Динамические цвета",
  dynamicOnHint: "Эти цвета нужны только в редакторе; телефон возьмёт цвета обоев.",
  dynamicOffHint: "Если включить, телефон берёт цвета обоев, а эти — запасные.",
  closeBtn: "Закрыть",
  screens: "Выбрать экран",
  noLayers: "На этом экране пока ничего нет",
  showParts: "Показать элементы внутри",
  hideParts: "Скрыть элементы внутри",
  lock: "Заблокировать",
  unlock: "Разблокировать",
  lockedGroup: "Группа заблокирована. Сначала разблокируйте её на панели слоёв",
  lockedKept: "Элементы заблокированной группы сохранены",
  lockedEdit: "Заблокировано. Выключите блокировку, чтобы править.",
  brief: "О чём это приложение…",
  appName: "Название приложения",
  targetPlatform: "Платформа",
  targetAndroid: "Собрать как нативное приложение Android",
  targetWeb: "Собрать как веб-приложение для браузера",
  copyPrompt: "Скопировать промпт",
  back: "Назад",
  close: "Закрыть",
  cancel: "Отмена",
  ok: "ОК",
  leading: "Начало",
  title: "Заголовок",
  body: "Текст",
  message: "Сообщение",
  placeholder: "Подсказка",
  regular: "Обычный",
  typeBody: "Основной",
  typeTitle: "Заголовок",
  typeHeadline: "Крупный заголовок",
  typeDisplay: "Дисплейный",
  trailing: "Конец",
  home: "Главная",
  screenN: "Экран",
  copySuffix: " копия",
  frameSize: "Размер экрана",
  phoneFrame: "Телефон",
  desktopFrame: "Компьютер",
  mobileNote: "Все возможности — в настольном браузере",
  addButton: "Добавить кнопку",
  linkHandle: "Перетащите на экран, чтобы задать переход",
  linkMade: "Переход задан",
  device: "Устройство",
  done: "Готово",
  theme: "Тема",
  settings: "Тема и настройки",
  shape: "Форма",
  typography: "Шрифт",
  motion: "Движение",
  brightness: "Яркость",
  light: "Светлая",
  dark: "Тёмная",
  contrast: "Контраст",
  bothModes: "Обе",
  contrastStandard: "Обычный",
  contrastMedium: "Средний",
  contrastHigh: "Высокий",
  shapeScale: "Скругление углов",
  shapeSquare: "Квадратные",
  shapeRounded: "Скруглённые",
  shapeFull: "Полностью круглые",
  design: "Вид",
  trigger: "Триггер",
  noteDialog: "Описание кнопки",
  partSpec: "Что делает этот элемент",
  toggleLookHint: "Два вида настраиваются на вкладке «Вид»",
  addFrameHint: "Добавьте экран, и сюда можно будет отправить нажатие",
  replay: "Воспроизвести ещё раз",
  toggleTitle: "Переключатель",
  whenPressedExample: "например: сохранить и вернуться к списку",
  resizeWidth: "Потяните, чтобы изменить ширину",
  resizeHeight: "Потяните, чтобы изменить высоту",
  resizeSize: "Потяните, чтобы изменить размер",
  openLink: "Открыть ссылку",
  fabPlain: "Обычная",
  fabExtended: "Расширенная",
  fabMenuAction: "Открыть меню",
  dropToRemove: "Убрать",
  reorder: "Изменить порядок",
  splitMain: "Основное действие",
  splitMenu: "Стрелка",
  selectDate: "Выберите дату",
  selectTime: "Выберите время",
  dateLabel: "Дата",
  hourLabel: "Часы",
  minuteLabel: "Минуты",
  layout: "Раскладка",
  carouselMultiBrowse: "Мультипросмотр",
  carouselUncontained: "Без контейнера",
  carouselHero: "Герой",
  carouselFullScreen: "Во весь экран",
  dateModal: "Модальный",
  dateDocked: "Встроенный",
  dateInput: "Ввод",
  timeDial: "Циферблат",
  cards: "Карточки",
  linkUrl: "Адрес ссылки",
  linkInvalid: "Введите корректный веб-адрес",
  linkBrowser: "Браузер",
  fullscreen: "Править во весь экран",
  exitFullscreen: "Закрыть полный экран",
  outline: "Структура",
  screenLook: "Цвет экрана",
  scrolling: "Прокрутка",
  screenLength: "Длина экрана",
  shapeHint:
    "Меняет скругление по умолчанию сразу у всех элементов. Радиус, заданный вручную, остаётся как есть.",
  fontFamily: "Гарнитура",
  emphasized: "Акцентные стили",
  emphasizedHint: "Заголовки и подписи используют более плотные стили M3 Expressive.",
  motionScheme: "Схема движения",
  motionStandard: "Стандартная",
  motionExpressive: "Выразительная",
  motionHint:
    "Выразительная — упругая пружина. Она управляет переходами в предпросмотре и промптом.",
  tryIt: "Нажмите, чтобы попробовать",
  tidy: "Упорядочить",
  tidyUndo: "Отменить упорядочивание",
  tidyDone: "Уже в порядке",
  placement: "Расположение",
  placeTop: "Сверху",
  placeCenter: "По центру",
  placeBottom: "Снизу",
  placeSpread: "Равномерно",
  align: "Выравнивание",
  alignLeft: "По левому краю",
  alignCenterH: "По центру по горизонтали",
  alignRight: "По правому краю",
  alignTop: "По верхнему краю",
  alignCenterV: "По центру по вертикали",
  alignBottom: "По нижнему краю",
  description: "Описание",
  screenDescription: "Для чего этот экран",
  ai: "ИИ",
  promptReset: "Вернуть сгенерированный промпт",
  aiWriteShort: "Написать с ИИ",
  aiWrite: "Поручить ИИ написать",
  aiSettings: "Настройки ИИ",
  aiProvider: "Провайдер",
  aiBaseUrl: "Базовый URL",
  aiModel: "ID модели",
  aiKey: "API-ключ",
  aiGetKey: "Получить ключ",
  aiKeyHint: "Хранится только в этом приложении и отправляется напрямую провайдеру.",
  aiRestore: "Переключить между версией ИИ и оригиналом",
  aiApplied: "Применено",
  aiSelectScreen: "Сначала выберите экран",
  aiNoKey: "Добавьте ключ на вкладке ИИ, чтобы пользоваться этим",
  aiError: "Запрос к ИИ не удался",
  aiErrorRefusal: "Модель отказалась отвечать",
  aiErrorJson: "Не удалось прочитать ответ модели",
  aiErrorLong: "Ответ оборвался. Попробуйте меньше экранов",
  aiErrorModel: "Введите ID модели",
  aiErrorInsecure: "Базовый URL должен быть https или указывать на localhost",
  aiErrorNetwork: "Не удалось подключиться. Проверьте URL, сеть и CORS на сервере",
};

/** Названия видов элементов (в палитре, слоях и инспекторе). */
export const RU_NOUN: Record<string, string> = {
  box: "Блок",
  bottomSheet: "Нижняя панель",
  button: "Кнопка",
  iconButton: "Кнопка-иконка",
  fab: "FAB",
  extendedFab: "Расширенная FAB",
  chip: "Чип",
  topAppBar: "Верхняя панель",
  bottomNav: "Панель навигации",
  navRail: "Навигационный рейл",
  searchBar: "Строка поиска",
  card: "Карточка",
  listItem: "Элемент списка",
  dialog: "Диалог",
  snackbar: "Снэкбар",
  textField: "Текстовое поле",
  select: "Выпадающий список",
  switch: "Переключатель",
  checkbox: "Флажок",
  slider: "Ползунок",
  text: "Текст",
  image: "Картинка",
  camera: "Камера",
  map: "Карта",
  divider: "Разделитель",
  loadingIndicator: "Индикатор загрузки",
  linearProgress: "Линейный прогресс",
  circularProgress: "Круговой прогресс",
  splitButton: "Раздельная кнопка",
  fabMenu: "Меню FAB",
  toolbar: "Плавающий тулбар",
  tabs: "Вкладки",
  radio: "Радиокнопка",
  carousel: "Карусель",
  datePicker: "Выбор даты",
  timePicker: "Выбор времени",
  banner: "Баннер",
  custom: "Свой элемент",
  avatar: "Аватар",
  segmentedButton: "Сегментная кнопка",
  tooltip: "Подсказка",
  menu: "Меню",
  rating: "Рейтинг",
};

export const RU_CATEGORY: Record<string, string> = {
  actions: "Действия",
  navigation: "Навигация",
  containment: "Контейнеры",
  inputs: "Ввод",
  content: "Содержимое",
  progress: "Прогресс",
};
