const RU = {
  select: "Выбор",
  hand: "Рука (пробел)",
  sticky: "Стикер",
  text: "Текст",
  shape: "Фигура",
  line: "Соединитель",
  frame: "Рамка",
  pen: "Карандаш",
  sticker: "Эмодзи",
  task: "Задача",
  image: "Картинка",
  note: "Заметка",
  undo: "Отменить",
  redo: "Повторить",
  templates: "Шаблоны",
  export: "Экспорт",
  exportPng: "Картинка PNG",
  exportSvg: "Векторная SVG",
  exportJson: "Файл .holst (JSON)",
  fit: "Показать всё",
  fitSel: "Показать выделенное",
  zoomIn: "Приблизить",
  zoomOut: "Отдалить",
  grid: "Сетка",
  snap: "Привязка к объектам",
  wheelZoom: "Колесо — масштаб",
  wheelPan: "Колесо — прокрутка",
  boards: "Доски",
  newBoard: "Новая доска",
  rename: "Переименовать",
  del: "Удалить",
  delBoard: "Удалить доску?",
  layers: "Слои",
  props: "Свойства",
  fill: "Заливка",
  stroke: "Контур",
  width: "Толщина",
  opacity: "Прозрачность",
  radius: "Скругление",
  shadow: "Тень",
  dash: "Линия",
  solid: "Сплошная",
  dashed: "Штрих",
  dotted: "Точки",
  fontSize: "Размер",
  bold: "Жирный",
  italic: "Курсив",
  alignL: "По левому краю",
  alignC: "По центру",
  alignR: "По правому краю",
  top: "Сверху",
  middle: "По центру",
  bottom: "Снизу",
  font: "Шрифт",
  textColor: "Цвет текста",
  align: "Выравнивание",
  distribute: "Распределить",
  group: "Сгруппировать",
  ungroup: "Разгруппировать",
  front: "На передний план",
  back: "На задний план",
  forward: "Вперёд",
  backward: "Назад",
  lock: "Закрепить",
  unlock: "Открепить",
  hide: "Скрыть",
  show: "Показать",
  duplicate: "Дублировать",
  copy: "Копировать",
  cut: "Вырезать",
  paste: "Вставить",
  selectAll: "Выбрать всё",
  delAll: "Удалить всё",
  edit: "Править текст",
  position: "Положение",
  rotation: "Поворот",
  lineStyle: "Вид соединителя",
  straight: "Прямая",
  curve: "Кривая",
  step: "Ломаная",
  startHead: "Начало",
  endHead: "Конец",
  none: "Нет",
  arrow: "Стрелка",
  triangle: "Треугольник",
  dot: "Точка",
  animated: "Бегущий пунктир",
  tidy: "Упорядочить",
  empty: "Двойной клик — создать текст. Перетащите сюда картинку или заметку.",
  hintHand: "Рука: тяните, чтобы двигать холст",
  saved: "Сохранено",
  saving: "Сохранение…",
  saveFail: "Не удалось сохранить",
  shortcuts: "Горячие клавиши",
  frameName: "Рамка",
  groupName: "Группа",
  tooBig: "Картинка слишком большая",
  align_left: "Влево",
  align_hcenter: "По центру (гор.)",
  align_right: "Вправо",
  align_top: "Вверх",
  align_vcenter: "По центру (верт.)",
  align_bottom: "Вниз",
  distH: "По горизонтали",
  distV: "По вертикали",
  pasteImage: "Картинка вставлена",
  sans: "Обычный",
  serif: "С засечками",
  mono: "Моно",
  hand_: "Рукописный",
  color: "Цвет",
  custom: "Свой цвет",
  layersEmpty: "Пока пусто",
  object: "Объект",
  dropHere: "Отпустите, чтобы добавить на доску",
  newName: "Название доски",
  copyOf: "копия",
};

const EN: typeof RU = {
  select: "Select",
  hand: "Hand (Space)",
  sticky: "Sticky",
  text: "Text",
  shape: "Shape",
  line: "Connector",
  frame: "Frame",
  pen: "Pen",
  sticker: "Emoji",
  task: "Task",
  image: "Image",
  note: "Note",
  undo: "Undo",
  redo: "Redo",
  templates: "Templates",
  export: "Export",
  exportPng: "PNG image",
  exportSvg: "SVG vector",
  exportJson: ".holst file (JSON)",
  fit: "Zoom to fit",
  fitSel: "Zoom to selection",
  zoomIn: "Zoom in",
  zoomOut: "Zoom out",
  grid: "Grid",
  snap: "Snap to objects",
  wheelZoom: "Wheel zooms",
  wheelPan: "Wheel scrolls",
  boards: "Boards",
  newBoard: "New board",
  rename: "Rename",
  del: "Delete",
  delBoard: "Delete board?",
  layers: "Layers",
  props: "Properties",
  fill: "Fill",
  stroke: "Stroke",
  width: "Width",
  opacity: "Opacity",
  radius: "Corner radius",
  shadow: "Shadow",
  dash: "Line",
  solid: "Solid",
  dashed: "Dashed",
  dotted: "Dotted",
  fontSize: "Size",
  bold: "Bold",
  italic: "Italic",
  alignL: "Align left",
  alignC: "Align center",
  alignR: "Align right",
  top: "Top",
  middle: "Middle",
  bottom: "Bottom",
  font: "Font",
  textColor: "Text color",
  align: "Align",
  distribute: "Distribute",
  group: "Group",
  ungroup: "Ungroup",
  front: "Bring to front",
  back: "Send to back",
  forward: "Forward",
  backward: "Backward",
  lock: "Lock",
  unlock: "Unlock",
  hide: "Hide",
  show: "Show",
  duplicate: "Duplicate",
  copy: "Copy",
  cut: "Cut",
  paste: "Paste",
  selectAll: "Select all",
  delAll: "Delete all",
  edit: "Edit text",
  position: "Position",
  rotation: "Rotation",
  lineStyle: "Connector style",
  straight: "Straight",
  curve: "Curved",
  step: "Elbow",
  startHead: "Start",
  endHead: "End",
  none: "None",
  arrow: "Arrow",
  triangle: "Triangle",
  dot: "Dot",
  animated: "Animated dashes",
  tidy: "Auto layout",
  empty: "Double-click to add text. Drop an image or a note here.",
  hintHand: "Hand: drag to pan the board",
  saved: "Saved",
  saving: "Saving…",
  saveFail: "Could not save",
  shortcuts: "Shortcuts",
  frameName: "Frame",
  groupName: "Group",
  tooBig: "Image is too large",
  align_left: "Left",
  align_hcenter: "Center (horizontal)",
  align_right: "Right",
  align_top: "Top",
  align_vcenter: "Center (vertical)",
  align_bottom: "Bottom",
  distH: "Horizontally",
  distV: "Vertically",
  pasteImage: "Image pasted",
  sans: "Sans",
  serif: "Serif",
  mono: "Mono",
  hand_: "Handwritten",
  color: "Color",
  custom: "Custom color",
  layersEmpty: "Nothing here yet",
  object: "Object",
  dropHere: "Drop to add to the board",
  newName: "Board name",
  copyOf: "copy",
};

export type Key = keyof typeof RU;
export const strings = (lang: string): ((k: Key) => string) => {
  const d = lang.toLowerCase().startsWith("ru") ? RU : EN;
  return (k) => d[k];
};
